import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:intl/intl.dart';
import '../models/report.dart';
import '../models/user_profile.dart';

class PdfReportService {
  static Future<Uint8List> generateReport({
    required HealthReport report,
    UserProfile? profile,
  }) async {
    final pdf = pw.Document();
    final dateFormatter = DateFormat('dd MMM yyyy, hh:mm a');

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        header: (context) => _buildHeader(dateFormatter.format(report.date)),
        footer: (context) => _buildFooter(context),
        build: (context) => [
          if (profile != null) _buildPatientInfo(profile),
          pw.SizedBox(height: 16),

          // High Risk Section
          if (report.highRiskDiseases.isNotEmpty)
            _buildRiskSection(
              'HIGH / CRITICAL RISK',
              report.highRiskDiseases.cast<String>(),
              PdfColors.red,
            ),

          // Moderate Risk Section
          if (report.moderateRiskDiseases.isNotEmpty)
            _buildRiskSection(
              'MODERATE RISK',
              report.moderateRiskDiseases.cast<String>(),
              PdfColors.orange,
            ),

          // Low Risk Section
          if (report.lowRiskDiseases.isNotEmpty)
            _buildRiskSection(
              'LOW RISK (WITHIN NORMAL)',
              report.lowRiskDiseases.cast<String>(),
              PdfColors.green,
            ),

          // Clinical Findings
          if (report.abnormalValues.isNotEmpty) ...[
            pw.SizedBox(height: 16),
            _buildFindingsSection(report.abnormalValues),
          ],

          // Disclaimer
          pw.SizedBox(height: 24),
          pw.Container(
            padding: const pw.EdgeInsets.all(12),
            decoration: pw.BoxDecoration(
              border: pw.Border.all(color: PdfColors.grey400),
              borderRadius: pw.BorderRadius.circular(4),
            ),
            child: pw.Text(
              'DISCLAIMER: This report is generated by an AI-powered health screening tool '
              'for informational purposes only. It is NOT a medical diagnosis. '
              'Always consult a qualified healthcare provider for medical decisions.',
              style: pw.TextStyle(
                fontSize: 8,
                color: PdfColors.grey600,
                fontStyle: pw.FontStyle.italic,
              ),
            ),
          ),
        ],
      ),
    );

    return pdf.save();
  }

  static pw.Widget _buildHeader(String dateStr) {
    return pw.Container(
      padding: const pw.EdgeInsets.only(bottom: 12),
      decoration: const pw.BoxDecoration(
        border: pw.Border(
            bottom: pw.BorderSide(color: PdfColors.blue800, width: 2)),
      ),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text('Health Check AI',
                  style: pw.TextStyle(
                      fontSize: 22,
                      fontWeight: pw.FontWeight.bold,
                      color: PdfColors.blue900)),
              pw.Text('Risk Assessment Report',
                  style: const pw.TextStyle(
                      fontSize: 12, color: PdfColors.grey700)),
            ],
          ),
          pw.Text(dateStr,
              style:
                  const pw.TextStyle(fontSize: 10, color: PdfColors.grey600)),
        ],
      ),
    );
  }

  static pw.Widget _buildFooter(pw.Context context) {
    return pw.Container(
      padding: const pw.EdgeInsets.only(top: 8),
      decoration: const pw.BoxDecoration(
        border: pw.Border(top: pw.BorderSide(color: PdfColors.grey300)),
      ),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text('Generated by Health Check AI',
              style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey500)),
          pw.Text('Page ${context.pageNumber} of ${context.pagesCount}',
              style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey500)),
        ],
      ),
    );
  }

  static pw.Widget _buildPatientInfo(UserProfile profile) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(12),
      decoration: pw.BoxDecoration(
        color: PdfColors.blue50,
        borderRadius: pw.BorderRadius.circular(4),
      ),
      child: pw.Row(
        children: [
          pw.Expanded(
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text('Patient: ${profile.name}',
                    style: pw.TextStyle(
                        fontSize: 14, fontWeight: pw.FontWeight.bold)),
                pw.SizedBox(height: 4),
                pw.Text(
                    'Age: ${profile.age} years  |  Gender: ${profile.gender}',
                    style: const pw.TextStyle(fontSize: 10)),
                if (profile.height != null && profile.weight != null)
                  pw.Text(
                      'Height: ${profile.height} cm  |  Weight: ${profile.weight} kg',
                      style: const pw.TextStyle(fontSize: 10)),
              ],
            ),
          ),
        ],
      ),
    );
  }

  static pw.Widget _buildRiskSection(
      String title, List<String> items, PdfColor color) {
    return pw.Container(
      margin: const pw.EdgeInsets.only(bottom: 12),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Container(
            padding: const pw.EdgeInsets.symmetric(horizontal: 8, vertical: 4),
            decoration: pw.BoxDecoration(
              color: color,
              borderRadius: pw.BorderRadius.circular(4),
            ),
            child: pw.Text(title,
                style: pw.TextStyle(
                    fontSize: 12,
                    fontWeight: pw.FontWeight.bold,
                    color: PdfColors.white)),
          ),
          pw.SizedBox(height: 6),
          ...items.map((item) => pw.Padding(
                padding: const pw.EdgeInsets.only(left: 8, bottom: 4),
                child: pw.Row(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Container(
                      width: 4,
                      height: 4,
                      margin: const pw.EdgeInsets.only(top: 3, right: 6),
                      decoration: pw.BoxDecoration(
                        shape: pw.BoxShape.circle,
                        color: color,
                      ),
                    ),
                    pw.Expanded(
                        child: pw.Text(item,
                            style: const pw.TextStyle(fontSize: 10))),
                  ],
                ),
              )),
        ],
      ),
    );
  }

  static pw.Widget _buildFindingsSection(List<String> findings) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text('CLINICAL FINDINGS',
            style: pw.TextStyle(
                fontSize: 14,
                fontWeight: pw.FontWeight.bold,
                color: PdfColors.blueGrey800)),
        pw.Divider(),
        ...findings.map((f) => pw.Padding(
              padding: const pw.EdgeInsets.only(bottom: 3),
              child: pw.Row(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Container(
                    width: 4,
                    height: 4,
                    margin: const pw.EdgeInsets.only(top: 4, right: 8),
                    decoration: const pw.BoxDecoration(
                        shape: pw.BoxShape.circle, color: PdfColors.blueGrey),
                  ),
                  pw.Expanded(
                      child:
                          pw.Text(f, style: const pw.TextStyle(fontSize: 9))),
                ],
              ),
            )),
      ],
    );
  }
}
