// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw7a6X_1yqS8Yb060dg2wVRabdkj58_iI',
    appId: '1:888391941492:web:2f46c02a816d61d0238021',
    messagingSenderId: '888391941492',
    projectId: 'diseasecheck-57cc2',
    authDomain: 'diseasecheck-57cc2.firebaseapp.com',
    storageBucket: 'diseasecheck-57cc2.firebasestorage.app',
    measurementId: 'G-R7LH9GEW6N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtKb9BdUagDxfJomdunKqQXMtemQLUd9o',
    appId: '1:888391941492:android:c78dde61097070bb238021',
    messagingSenderId: '888391941492',
    projectId: 'diseasecheck-57cc2',
    storageBucket: 'diseasecheck-57cc2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzeogsB7SsLChBAe7S08mJHvq7EGmEWf0',
    appId: '1:888391941492:ios:d81c7fcded9a7368238021',
    messagingSenderId: '888391941492',
    projectId: 'diseasecheck-57cc2',
    storageBucket: 'diseasecheck-57cc2.firebasestorage.app',
    iosBundleId: 'com.healthcheck.diseaseCheckApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzeogsB7SsLChBAe7S08mJHvq7EGmEWf0',
    appId: '1:888391941492:ios:d81c7fcded9a7368238021',
    messagingSenderId: '888391941492',
    projectId: 'diseasecheck-57cc2',
    storageBucket: 'diseasecheck-57cc2.firebasestorage.app',
    iosBundleId: 'com.healthcheck.diseaseCheckApp',
  );
}
